### ISSUE TITLE
a question about the requirements

### ISSUE THREAD

**Issue by VinsonBlue** [look4pritam/tfmtcnn#1]
What is the python's and tensor-flow's  version you  used in this project ! @look4pritam

**Comment by look4pritam** [comment]
Python 2.7
TensorFlow 1.6

**Comment by look4pritam** [comment]
Do not use **master** branch, use **CelebA** branch. It provides much better results.
It works with TensorFlow 1.8 with some warnings.

**Comment by look4pritam** [comment]
Now closing it.
