### ISSUE TITLE
How to convert three ckpt file into one pb?

### ISSUE THREAD

**Issue by BrownOfSummer** [look4pritam/tfmtcnn#11]
How to convert the three models of PNet, RNet, Onet into single pb file, so it can be more simple to deploy

**Comment by look4pritam** [comment]
Currently there is no provision for freezing the models. Use following URL for model freezing https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc
I will be happy accept pull request.
