### ISSUE TITLE
Generate simple dataset is too slow.

### ISSUE THREAD

**Issue by BrownOfSummer** [look4pritam/tfmtcnn#12]
It is too slow for running generate_simple_dataset.py, more 20 hours only get this:
_(64000/12491) number of images are done - positive - 638825,  part - 701921, negative - 2043184
(65000/12491) number of images are done - positive - 648560,  part - 712855, negative - 2060120
(66000/12491) number of images are done - positive - 658636,  part - 723811, negative - 2078176_

Why you set the **default_base_number_of_images**=700K, and how to **speed up** the generate speed ?

**Comment by look4pritam** [comment]
It doesn't take that much time. You can try to set --base_number_of_images to 500000 or less.

**Comment by look4pritam** [comment]
Is your RAM size less than 8GB? If yes then that maybe the reason.

**Comment by BrownOfSummer** [comment]
After read your code, I think the reason is **"base_number_of_attempts = 5000"**; This may result into too many attempts; I will try when it set to 100.

**Comment by look4pritam** [comment]
reducing base_number_of_attempts = 5000 to 100 will save your time. Once dataset is generated keep tensorflow dataset files for future use. In this way you can experiment with diff model parameters.
PNet dataset is generated in < 24 Hr, RNet takes ~ 24 Hrs, ONet takes ~ 1.5 Day.

**Comment by ingjieye** [comment]
> reducing base_number_of_attempts = 5000 to 100 will save your time. Once dataset is generated keep tensorflow dataset files for future use. In this way you can experiment with diff model parameters.
> PNet dataset is generated in < 24 Hr, RNet takes ~ 24 Hrs, ONet takes ~ 1.5 Day.

How come it take that so much time to generate dataset ?
