### ISSUE TITLE
webcamera_demo.py location

### ISSUE THREAD

**Issue by yoterel** [look4pritam/tfmtcnn#13]
Tried to run out of the box the web camera demo, but since webcamera_demo.py imports tfmtcnn and is in the same directory as the package, it wouldn't import anything (windows 7, python 3.7.3).

I solved by moving webcamera_demo.py up one level, and running it from there, maybe this should be fixed in master branch ?

To reproduce simply download the master zip file, extract, and open command line, then run "python tftcnn\webcamera_demo.py"

**Comment by look4pritam** [comment]
It is not able to find python module tfmtcnn. 
export tfmtcnn/tfmtcnn folder on PYTHONPATH. This will solve your problem. There is no need to move webcamera_demo.py file.
Thank you very much for checking this code on Windows. It is good to know that it works on Windows.
