### ISSUE TITLE
Accuracy comparison to the original MTCNN?

### ISSUE THREAD

**Issue by utkarsh-VRL** [look4pritam/tfmtcnn#14]
Hi @look4pritam ,

Can you comment on the accuracy of this implementation compared with the original? Something similar to [https://github.com/Seanlinx/mtcnn#results](https://github.com/Seanlinx/mtcnn#results)

Thank you

**Comment by look4pritam** [comment]
With 0.7, 0.6, 0.6 as threshold and minimum face size = 20 accuracy is 94.5
on same dataset as that used in original paper.

Original paper is having 95.0 accuracy.
Given link shows 92.5 accuracy.

The model is small, so gets overfit easily.
I have avoided it. Still some more work is needed.
