### ISSUE TITLE
RNet data preparation

### ISSUE THREAD

**Issue by Sheethal00** [look4pritam/tfmtcnn#18]
Hi,

I have some question relation to RNet data preparation

While generating tf records for RNet model
-> For image samples it generates positive,negative,part tf records separately unlike PNet model where the tf records is generated for the img_list where it has positive,negative,part and landmark data
-> For landmark samples img_list is used to generate tf record where it has positive,negative,part and landmark data

My question is positive,negative,part samples are used both while genarting tf records for image sample and landmark samples

Is it done deliberately??

Thanks in advance

**Comment by look4pritam** [comment]
Samples for PNet are generated offline, whereas for RNet and ONet some
samples are generated online and a small fraction is generated offline.
Online samples improve accuracy.

**Comment by Sheethal00** [comment]
I mean positive,negative and part samples are used twice.

In the below attached file

-> At line number 71,79 and 88 tf records are generated for positive,part,negative respectively
-> At line number 95 tf record is generated for landmark using image_list, where image list has landmark data along with positive,negative,part data

Could you please tell me the reason for using positive,negative,part data twice

Thanks
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/65819572/107345345-781ca700-6ae9-11eb-8b2a-3d1e75209612.png">

**Comment by look4pritam** [comment]
Positive, negative, and part are generated from wider face and celebs
datasets both.
Celebs contains landmarks, wider face is without landmarks.

PNet contains only offline samples.
RNet, ONet contain both online and offline samples.

**Comment by Sheethal00** [comment]
Closing the issue
