### ISSUE TITLE
A problem in the label list

### ISSUE THREAD

**Issue by VinsonBlue** [look4pritam/tfmtcnn#2]
There is a wrong label data in the wider_face_train_bbx_gt.txt at line 161871
![1](https://user-images.githubusercontent.com/28971551/41719579-08a30c96-7593-11e8-83a5-9c4a7fb70e35.JPG)

**Comment by look4pritam** [comment]
You can replace this ground truth bounding box file by wider face dataset
file. Just check with wider face dataset ground truth file.

**Comment by look4pritam** [comment]
Now closing it.
